CFLAGS=-Wall -Wextra -Wpedantic -pedantic-errors -g -O2 -std=c11

all:
	make ex1
	make ex3
	make ex4
	make ex5
	make ex6
	make ex7
	make ex8
	make ex9

clean:
	find -regextype posix-extended -regex "./ex[0-9]+" -exec rm -rf {} \;
