# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define :arch do |arch|
    arch.vm.box = 'generic/arch'
    arch.vm.box_version = '= 3.2.8'
    arch.vm.network 'private_network', ip: "10.13.37.2"
    arch.vm.provider :parallels do |p|
      p.name = 'arch'
      p.memory = 1024
      p.cpus = 1
      p.customize ['set', :id, '--hypervisor-type', 'apple', '--adaptive-hypervisor', 'off']
    end
    arch.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    arch.vm.provision 'shell', privileged: true, inline: <<-SHELL
      echo 'Server = https://ftp.rnl.tecnico.ulisboa.pt/pub/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
      pacman -Syyu --noconfirm --ignore linux &>/dev/null
      pacman -S podman podman-docker podman-compose --noconfirm --needed &>/dev/null
      echo 'vagrant:165536:65536' > /etc/subuid
      echo 'vagrant:165536:65536' > /etc/subgid
      sed -i 's/driver = ""/driver = "overlay"/g' /etc/containers/storage.conf
    SHELL
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ecdsa.pub").first.strip
    arch.vm.provision 'shell', privileged: false, inline: <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      systemctl enable --user podman.socket --now &>/dev/null
    SHELL
  end
end
