#!/bin/sh
git clone git@github.com:pineman/abra.git proj/abra
git clone git@github.com:pineman/blackjack.git proj/blackjack
git clone git@github.com:pineman/wordmorph.git proj/wordmorph
git clone git@github.com:pineman/wordfind.git proj/wordfind
git clone git@github.com:hackerschool/ledmatrix.git proj/LEDmatrix
git clone git@github.com:hackerschool/r2p.git proj/r2p
git clone git@github.com:pineman/psis proj/psis
git clone git@github.com:pineman/pineman.github.io.git proj/homepage
git clone git@github.com:pineman/services.git proj/services
git clone git@gitlab.com:pineman/ju.git proj/ju
git clone git@github.com:pineman/abra-go.git proj/abra-go
git clone git@github.com:pineman/aoc.git chall/aoc
git clone https://github.com/github/gitignore git/gitignore
git clone https://github.com/sasa1977/elixir-in-action elixir/elixir-in-action
git clone https://github.com/sasa1977/demo_system elixir/demo_system
git clone https://github.com/dnlserrano/elixir-workshop elixir/elixir-workshop
git clone https://github.com/sasa1977/aoc elixir/aoc
git clone https://github.com/quii/learn-go-with-tests go/learn-go-with-tests
