# frozen_string_literal: true

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

require 'rubocop/rake_task'
RuboCop::RakeTask.new do |t|
  t.fail_on_error = false
end

task :fasterer do
  # empty block allows cmd to fail without exiting rake
  system 'bundle exec fasterer'
end

require 'reek/rake/task'
Reek::Rake::Task.new do |t|
  t.fail_on_error = false
end

task default: :spec

task :autolint do
  system 'bundle exec rake rubocop:auto_correct &>/dev/null'
end

# task lint: %i[rubocop fasterer reek]
task lint: %i[rubocop reek]

task :run do
  ruby 'lib/hello.rb'
end
