#!usr/bin/python3

"""
EULER 2
http://projecteuler.net/problem=2
----------------------------------
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Separando as variáveis

a = 0
b = 1
soma = 0
while (a+b) < 4000000:
    if (a+b) % 2 == 0:
        soma += (a+b)
    c = a
    a = b
    b = c+b

    
print(soma)

# Juntando-as (so pythonic)

a, b = 0, 1
soma2 = 0
while (a+b) < 4000000:
    if (a+b) % 2 == 0:
        soma2 += a+b
    a, b = b, a+b
print(soma2)