#!/bin/sh

# http://planzero.org/blog/2012/10/24/hosting_an_admin-friendly_git_server_with_git-shell

# If no project name is given
if [ $# -ne 1 ]
then
	# Display usage and stop
	echo "Usage: new <project.git>"
	exit 1

fi

# Set the project name, adding .git if necessary
project=$(echo "$*" | sed 's/\.git$\|$/.git/i')

# Create and initialise the project
mkdir "$project" && \
cd "$project" && \
git --bare init
