# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'ruby-debug-ide', '0.7.3', require: false
  gem 'debase', '0.2.5.beta2', require: false
  gem 'solargraph', '0.48.0', require: false
end
