require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/LineLength:
  Max: 80
  AutoCorrect: true