# frozen_string_literal: true

source 'https://rubygems.org'
gem 'rspec', '~> 3.10', require: false
group :dev do
  gem 'fasterer', '~> 0.9.0', require: false
  gem 'guard', '~> 2.16', '>= 2.16.2', require: false
  gem 'guard-rake', '~> 1.0', require: false
  gem 'guard-rspec', '~> 4.7', '>= 4.7.3', require: false
  gem 'rake', '~> 13.0', '>= 13.0.3', require: false
  gem 'reek', '~> 6.0', '>= 6.0.3', require: false
  gem 'rubocop', '~> 1.10', require: false
  gem 'rubocop-performance', '~> 1.9', '>= 1.9.2', require: false
  gem 'rubocop-rake', '~> 0.5.1', require: false
  gem 'rubocop-rspec', '~> 2.2', require: false
end
